# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='people',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u5b57')),
                ('age', models.IntegerField(default=0, verbose_name='\u5e74\u9f84')),
                ('sex', models.CharField(choices=[(0, '\u7537'), (1, '\u5973')], max_length=2, verbose_name='\u6027\u522b')),
                ('img', models.ImageField(upload_to=b'', verbose_name='\u5934\u50cf')),
                ('info', models.TextField(default='', verbose_name='\u7b80\u4ecb')),
                ('title', models.CharField(choices=[(0, '\u8bb2\u5e08'), (1, '\u526f\u6559\u6388'), (2, '\u6559\u6388'), (3, '\u9662\u58eb')], max_length=10, verbose_name='\u804c\u79f0')),
                ('email', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1')),
                ('major', models.CharField(max_length=250, verbose_name='\u7814\u7a76\u65b9\u5411')),
            ],
        ),
    ]
