# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpscil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='sex',
            field=models.IntegerField(choices=[(0, '\u7537'), (1, '\u5973')], default=0, verbose_name='\u6027\u522b'),
        ),
        migrations.AlterField(
            model_name='people',
            name='title',
            field=models.IntegerField(choices=[(0, '\u8bb2\u5e08'), (1, '\u526f\u6559\u6388'), (2, '\u6559\u6388'), (3, '\u9662\u58eb')], default=0, verbose_name='\u804c\u79f0'),
        ),
    ]
