# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hpscil', '0002_auto_20170504_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='\u6807\u9898')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('time', models.DateField(default=django.utils.timezone.now, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('author', models.CharField(max_length=30, verbose_name='\u7f16\u8f91')),
                ('img', models.ImageField(upload_to=b'', verbose_name='\u7f29\u7565\u56fe')),
            ],
        ),
        migrations.AlterField(
            model_name='people',
            name='info',
            field=models.TextField(default='\u4e3b\u4eba\u5f88\u61d2\uff0c\u4ec0\u4e48\u4e5f\u6ca1\u6709\u7559\u4e0b!', verbose_name='\u7b80\u4ecb'),
        ),
    ]
