# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpscil', '0003_auto_20170504_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='teamInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='HPSCIL', max_length=50, verbose_name='\u56e2\u961f\u540d\u79f0')),
                ('address', models.CharField(default='\u6e56\u5317\u7701\u6b66\u6c49\u5e02\u6d2a\u5c71\u533a\u9c81\u78e8\u8def388\u53f7\u4e2d\u56fd\u5730\u8d28\u5927\u5b66\uff08\u6b66\u6c49\uff09', max_length=250, verbose_name='\u5b9e\u9a8c\u5ba4\u5730\u5740')),
                ('postcode', models.CharField(default='430074', max_length=10, verbose_name='\u90ae\u7f16')),
                ('email', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1')),
                ('tel', models.CharField(default='', max_length=11)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(max_length=30, verbose_name='\u7f16\u8f91\u4eba'),
        ),
    ]
