# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hpscil', '0004_auto_20170504_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='\u6807\u9898')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('time', models.DateField(default=django.utils.timezone.now, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('author', models.CharField(max_length=30, verbose_name='\u7f16\u8f91\u4eba')),
                ('img', models.ImageField(upload_to=b'', verbose_name='\u7f29\u7565\u56fe')),
            ],
        ),
    ]
