# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 13:05
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hpscil', '0005_research'),
    ]

    operations = [
        migrations.CreateModel(
            name='hitCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='people',
            name='info',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='\u4e3b\u4eba\u5f88\u61d2\uff0c\u4ec0\u4e48\u4e5f\u6ca1\u6709\u7559\u4e0b!', verbose_name='\u7b80\u4ecb'),
        ),
        migrations.AlterField(
            model_name='research',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='\u5185\u5bb9'),
        ),
        migrations.AddField(
            model_name='hitcount',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hpscil.news'),
        ),
    ]
