# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 01:33
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hpscil', '0006_auto_20170505_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminfo',
            name='info',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='\u8be6\u7ec6\u4ecb\u7ecd'),
        ),
    ]
