# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hpscil', '0007_teaminfo_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminfo',
            name='qrcode',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=b'', verbose_name='\u4e8c\u7ef4\u7801'),
            preserve_default=False,
        ),
    ]
