# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 02:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hpscil', '0008_teaminfo_qrcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaminfo',
            name='qrcode',
        ),
    ]
