# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpscil', '0010_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='img',
            field=models.ImageField(upload_to=b'', verbose_name='\u8f6e\u64ad\u56fe'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='info',
            field=models.CharField(max_length=100, verbose_name='\u7b80\u4ecb'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='title',
            field=models.CharField(max_length=100, verbose_name='\u6807\u9898'),
        ),
    ]
