# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpscil', '0011_auto_20170513_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='info',
            field=models.CharField(max_length=100, null=True, verbose_name='\u7b80\u4ecb'),
        ),
    ]
