# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpscil', '0013_auto_20170513_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, verbose_name='\u6d3b\u4e3b\u9898')),
            ],
        ),
    ]
