# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hpscil', '0015_auto_20170513_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u65f6\u95f4'),
        ),
    ]
