# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 06:20
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpscil', '0016_auto_20170513_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='topic',
            field=models.CharField(max_length=100, verbose_name='\u6d3b\u52a8\u4e3b\u9898'),
        ),
    ]
