# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hpscil', '0017_auto_20170513_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='thumbnail',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=b'', verbose_name='\u6d3b\u52a8\u7f29\u7565\u56fe'),
            preserve_default=False,
        ),
    ]
