# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpscil', '0018_activity_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='degree',
            field=models.CharField(choices=[(0, '\u535a\u58eb\u540e'), (1, '\u535a\u58eb'), (2, '\u7855\u58eb'), (3, '\u672c\u79d1'), (4, '\u5f80\u5c4a\u6bd5\u4e1a\u751f')], default='', max_length=15, verbose_name='\u5b66\u4f4d'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='img',
            field=models.ImageField(upload_to=b'', verbose_name='\u8f6e\u64ad\u56fe(\u9ad8\u5ea6:400px)'),
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='tel',
            field=models.CharField(default='', max_length=11, verbose_name='\u8054\u7cfb\u65b9\u5f0f'),
        ),
    ]
