# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpscil', '0020_auto_20170514_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='isleadship',
            field=models.IntegerField(choices=[(0, '\u662f'), (1, '\u5426')], default=1, verbose_name='\u9886\u5bfc\u5c0f\u7ec4'),
        ),
        migrations.AlterField(
            model_name='people',
            name='title',
            field=models.IntegerField(choices=[(0, '\u8bb2\u5e08'), (1, '\u526f\u6559\u6388'), (2, '\u6559\u6388'), (3, '\u9662\u58eb'), (4, '\u65e0')], default=0, verbose_name='\u804c\u79f0'),
        ),
    ]
