# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpscil', '0021_auto_20170514_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='isleadship',
            field=models.IntegerField(choices=[(0, '\u5426'), (1, '\u662f')], default=0, verbose_name='\u9886\u5bfc\u5c0f\u7ec4'),
        ),
    ]
