# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpscil', '0022_auto_20170514_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='degree',
            field=models.IntegerField(choices=[(0, '\u535a\u58eb\u540e'), (1, '\u535a\u58eb'), (2, '\u7855\u58eb'), (3, '\u672c\u79d1'), (4, '\u5f80\u5c4a\u6bd5\u4e1a\u751f')], default=2, verbose_name='\u5b66\u4f4d'),
        ),
    ]
