# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hpscil', '0023_auto_20170514_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='trends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='\u6807\u9898')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u65f6\u95f4')),
                ('url', models.URLField(verbose_name='\u94fe\u63a5\u5730\u5740')),
            ],
        ),
    ]
