# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hpscil', '0024_trends'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='trends',
            new_name='tb_trends',
        ),
    ]
