# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpscil', '0025_auto_20170514_1927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='carousel',
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(upload_to=b'', verbose_name='\u8f6e\u64ad\u56fe(\u9ad8\u5ea6:400px)'),
        ),
    ]
